---
- hosts: all
  become: yes

  #  vars_files:
  #        - vars.yaml

  pre_tasks:
          - name: Update apt cache if needed
            apt: "update_cache=yes cache_valid_time=3600"
         
          # - debug: var=repo_stat
          - name: Check if the git repository exists
            stat: path=/opt/yolo
            register: repo_stat

          - name: Fetch the kitmikai/yolo GitHub repository
            git:
                    repo: https://github.com/kitmikai/yolo.git
                    dest: /opt/yolo
            when: not repo_stat.stat.exists

  tasks:
          # Install nodejs and npm on the client host
          - block:
                  - name: Install nodejs and npm on the client host 
                    apt:
                           state: present
                           name:
                                  - nodejs
                                  - npm
                  - name:  Check git repo folder exists.
                    stat: path=/opt/yolo/client
                    register: git_stat

                  - name: Copy the client directory to vagrant
                    command: mv /opt/yolo/client /home/vagrant
                    when: git_stat.stat.exists

                  - name: Install required modules in package.json
                    command: >
                            chdir=/home/vagrant/client
                            npm install

                  - name: Start the app
                    command: >
                            chdir=/home/vagrant/client 
                            npm start &

